# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

  Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	  config.ssh.insert_key = false
	  config.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm", :id, "--memory", "512"]

	  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      # The nolock option can be useful for an NFSv3 client that wants to avoid the
      # NLM sideband protocol. Without this option, apt-get might hang if it tries
      # to lock files needed for /var/cache/* operations. All of this can be avoided
      # by using NFSv4 everywhere. Please note that the tcp option is not the default.
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
  end

# Application server 1.
	config.vm.define "app1" do |app1|
		app1.vm.synced_folder ".", "/vagrant", type: "nfs"
		app1.vm.hostname = "app1"
		app1.vm.box = "centos/7"
		app1.vm.network :private_network, ip: "192.168.60.4"
    app1.vm.network "forwarded_port", guest: 80, host: 8080
	end

# Application server 2.
    config.vm.define "app2" do |app2|
		app2.vm.hostname = "app2"
        app2.vm.box = "bodgit/openbsd-5.7-amd64"
		app2.vm.network :private_network, ip: "192.168.60.5"
    end

# Bom e velho Slackware.
     config.vm.define "slack" do |slack|
        slack.vm.hostname = "slack2"
        slack.vm.synced_folder ".", "/vagrant", type: "nfs"
        slack.vm.box = "ricardson/slackware64-14.1-minimal"
        slack.vm.network :private_network, ip: "192.168.60.6"
    end

# Database server.
#     config.vm.define "db" do |db|
#        db.vm.hostname = "db"
#        db.vm.box = "ubuntu/trusty64"
#        db.vm.network :private_network, ip: "192.168.60.6"
#    end
   
end
